GET http://localhost:3001/todos

###
POST  http://localhost:3001/todo/new
Content-Type: application/json

{
    "text":"start learning for shell.ai"
}

###

DELETE http://localhost:3001/todo/delete/63d68f37fb53fb8b8deede4a

###
PUT http://localhost:3001/todo/complete/63d68f41fb53fb8b8deede4d